import "@testing-library/jest-dom";
import { vi } from "vitest";

// Mock window.orun (full structure matching preload.cjs) — only in jsdom/ browser environments
if (typeof window !== "undefined") {
Object.defineProperty(window, "orun", {
  value: {
    ai: {
      chat: vi.fn().mockResolvedValue(""),
      chatStream: vi.fn().mockReturnValue(() => {}),
      autonomous: vi.fn().mockReturnValue(() => {}),
      testConnection: vi.fn().mockResolvedValue({ ok: false }),
      listOllamaModels: vi.fn().mockResolvedValue([]),
      listCloudModels: vi.fn().mockResolvedValue([]),
      knownFreeModels: vi.fn().mockResolvedValue({}),
      modelCatalog: vi.fn().mockResolvedValue({}),
      providers: vi.fn().mockResolvedValue([]),
      usageToday: vi.fn().mockResolvedValue([]),
      healthCheck: vi.fn().mockResolvedValue({}),
      cacheStats: vi.fn().mockResolvedValue({ entries: 0, hits: 0, misses: 0, hitRate: 0 }),
      cacheClear: vi.fn().mockResolvedValue({ ok: true }),
      telemetry: vi.fn().mockResolvedValue({ counters: {}, metrics: {}, recentTraces: 0 }),
      rateLimitStatus: vi.fn().mockResolvedValue({}),
    },
    settings: {
      get: vi.fn().mockResolvedValue(undefined),
      set: vi.fn().mockResolvedValue(true),
      setApiKey: vi.fn().mockResolvedValue(true),
      hasApiKey: vi.fn().mockResolvedValue(false),
      setProviderKey: vi.fn().mockResolvedValue(true),
      deleteProviderKey: vi.fn().mockResolvedValue(true),
      providerKeyCount: vi.fn().mockResolvedValue(0),
      validateApiKey: vi.fn().mockResolvedValue({ valid: false }),
      isFirstRun: vi.fn().mockResolvedValue(false),
      encryptDB: vi.fn().mockResolvedValue({ ok: true }),
      decryptDB: vi.fn().mockResolvedValue({ ok: true }),
      isDBEncrypted: vi.fn().mockResolvedValue(false),
    },
    conversations: {
      list: vi.fn().mockResolvedValue([]),
      create: vi.fn().mockResolvedValue({ id: "test", title: "Test" }),
      messages: vi.fn().mockResolvedValue([]),
      addMessage: vi.fn().mockResolvedValue(true),
      remove: vi.fn().mockResolvedValue(undefined),
      truncateFrom: vi.fn().mockResolvedValue(true),
      importConversation: vi.fn().mockResolvedValue({ success: true }),
    },
    window: {
      minimize: vi.fn().mockResolvedValue(true),
      maximize: vi.fn().mockResolvedValue(true),
      close: vi.fn().mockResolvedValue(true),
      isMaximized: vi.fn().mockResolvedValue(false),
    },
    tts: {
      listVoices: vi.fn().mockResolvedValue([]),
      synthesize: vi.fn().mockResolvedValue({ audioBase64: "", mime: "audio/mp3" }),
      engines: vi.fn().mockResolvedValue([]),
      setEngineConfig: vi.fn().mockResolvedValue(true),
      getEngineConfig: vi.fn().mockResolvedValue({}),
      usageToday: vi.fn().mockResolvedValue([]),
    },
    stt: {
      engines: vi.fn().mockResolvedValue([]),
      testConnection: vi.fn().mockResolvedValue({ ok: false }),
      transcribe: vi.fn().mockResolvedValue({ text: "" }),
      transcribeGroq: vi.fn().mockResolvedValue({ text: "" }),
    },
    nutrition: {
      getDaily: vi.fn().mockResolvedValue({ entries: [], totals: { calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 } }),
      getRange: vi.fn().mockResolvedValue({ entries: [], daily: [] }),
    },
    finance: {
      getDaily: vi.fn().mockResolvedValue({ entries: [], totals: { income: 0, expenses: 0 }, balance: 0 }),
      getRange: vi.fn().mockResolvedValue({ entries: [], daily: [], totals: { income: 0, expenses: 0 }, balance: 0 }),
    },
    health: {
      getDaily: vi.fn().mockResolvedValue([]),
      getRange: vi.fn().mockResolvedValue([]),
    },
    developer: {
      getReviews: vi.fn().mockResolvedValue([]),
      getRange: vi.fn().mockResolvedValue({ entries: [], daily: [] }),
      setWorkspace: vi.fn().mockResolvedValue({ ok: true }),
      getWorkspace: vi.fn().mockResolvedValue(null),
      listFiles: vi.fn().mockResolvedValue([]),
    },
    teacher: {
      getProgress: vi.fn().mockResolvedValue([]),
      getRange: vi.fn().mockResolvedValue({ entries: [], daily: [] }),
    },
    app: {
      setRunInBackground: vi.fn().mockResolvedValue(true),
      checkForUpdates: vi.fn().mockResolvedValue({ ok: false }),
      installUpdate: vi.fn().mockResolvedValue(false),
      onUpdateStatus: vi.fn().mockReturnValue(() => {}),
      onNotify: vi.fn().mockReturnValue(() => {}),
    },
    n8n: {
      listWorkflows: vi.fn().mockResolvedValue([]),
      testConnection: vi.fn().mockResolvedValue({ ok: false }),
      triggerWebhook: vi.fn().mockResolvedValue({ ok: false }),
    },
    automation: {
      listRules: vi.fn().mockResolvedValue([]),
      addRule: vi.fn().mockResolvedValue({ ok: true, rules: [] }),
      removeRule: vi.fn().mockResolvedValue({ ok: true, rules: [] }),
      toggleRule: vi.fn().mockResolvedValue({ ok: true, rules: [] }),
    },
    socialMedia: {
      getConfig: vi.fn().mockResolvedValue({}),
      setConfig: vi.fn().mockResolvedValue(true),
      publish: vi.fn().mockResolvedValue({ ok: false }),
      publishMulti: vi.fn().mockResolvedValue([]),
      test: vi.fn().mockResolvedValue({}),
    },
    musicProducer: {
      getProjects: vi.fn().mockResolvedValue([]),
      getRange: vi.fn().mockResolvedValue({}),
      wonderaModels: vi.fn().mockResolvedValue([]),
      autotonePresets: vi.fn().mockResolvedValue([]),
      generateMusic: vi.fn().mockResolvedValue({ ok: false }),
      master: vi.fn().mockResolvedValue({ ok: false }),
      separateStems: vi.fn().mockResolvedValue({ ok: false }),
      autotone: vi.fn().mockResolvedValue({ ok: false }),
      mix: vi.fn().mockResolvedValue({ ok: false }),
      applyGain: vi.fn().mockResolvedValue({ ok: false }),
    },
    homeAssistant: {
      getConfig: vi.fn().mockResolvedValue({ mode: "simulated", host: "", token: "", name: "", connected: false, simulated: true }),
      setConfig: vi.fn().mockResolvedValue({ mode: "simulated", host: "", token: "", name: "", connected: false, simulated: true }),
      getDevices: vi.fn().mockResolvedValue([]),
      getRooms: vi.fn().mockResolvedValue([]),
      getStates: vi.fn().mockResolvedValue({ mode: "simulated", states: [] }),
      getDeviceState: vi.fn().mockResolvedValue({ success: false, error: "not found" }),
      callService: vi.fn().mockResolvedValue({ success: true }),
      getAutomations: vi.fn().mockResolvedValue([]),
      runAutomation: vi.fn().mockResolvedValue({ success: true }),
      createAutomation: vi.fn().mockResolvedValue({ success: true }),
      deleteAutomation: vi.fn().mockResolvedValue({ success: true }),
      toggleAutomation: vi.fn().mockResolvedValue({ success: true }),
      getScenes: vi.fn().mockResolvedValue([]),
      activateScene: vi.fn().mockResolvedValue({ success: true }),
      getStatus: vi.fn().mockResolvedValue(null),
    },
    security: {
      runAudit: vi.fn().mockResolvedValue(null),
      getReport: vi.fn().mockResolvedValue(null),
      fixFinding: vi.fn().mockResolvedValue({ success: false }),
      exportReport: vi.fn().mockResolvedValue({ ok: false }),
    },
    schedules: {
      get: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue(true),
    },
    healthGoals: {
      get: vi.fn().mockResolvedValue(null),
      set: vi.fn().mockResolvedValue(true),
      weeklyWeight: vi.fn().mockResolvedValue({}),
      logWeight: vi.fn().mockResolvedValue(true),
    },
    agenda: {
      get: vi.fn().mockResolvedValue([]),
      add: vi.fn().mockResolvedValue(true),
      clear: vi.fn().mockResolvedValue(true),
    },
    nutritionFile: {
      getToday: vi.fn().mockResolvedValue(null),
    },
    mcp: {
      listServers: vi.fn().mockResolvedValue([]),
      addServer: vi.fn().mockResolvedValue({ ok: false }),
      removeServer: vi.fn().mockResolvedValue({ ok: true }),
      listTools: vi.fn().mockResolvedValue([]),
    },
    plugins: {
      list: vi.fn().mockResolvedValue([]),
      load: vi.fn().mockResolvedValue({}),
      unload: vi.fn().mockResolvedValue({}),
      loadAll: vi.fn().mockResolvedValue([]),
    },
    skills: {
      list: vi.fn().mockResolvedValue([]),
      details: vi.fn().mockResolvedValue({ ok: false, error: "not found" }),
      install: vi.fn().mockResolvedValue({ ok: true }),
      installDialog: vi.fn().mockResolvedValue({ ok: false, canceled: true }),
      uninstall: vi.fn().mockResolvedValue({ ok: true }),
      setEnabled: vi.fn().mockResolvedValue({ ok: true }),
      reload: vi.fn().mockResolvedValue({ ok: true, order: [] }),
      tools: vi.fn().mockResolvedValue([]),
      dir: vi.fn().mockResolvedValue(""),
      openDir: vi.fn().mockResolvedValue({ ok: true }),
    },
    memory: {
      save: vi.fn().mockResolvedValue({ ok: true }),
      search: vi.fn().mockResolvedValue({ results: [], method: "empty" }),
      inject: vi.fn().mockResolvedValue(""),
      consolidate: vi.fn().mockResolvedValue({ ok: false, reason: "sem memórias maduras" }),
      remove: vi.fn().mockResolvedValue({ ok: true, removed: 0 }),
      stats: vi.fn().mockResolvedValue({ total: 0, withEmbedding: 0, byScope: {}, sizeKB: 0 }),
      list: vi.fn().mockResolvedValue([]),
    },
    knowledge: {
      save: vi.fn().mockResolvedValue({ ok: true }),
      changelog: vi.fn().mockResolvedValue({ ok: true }),
      diary: vi.fn().mockResolvedValue({ ok: true }),
      adr: vi.fn().mockResolvedValue({ ok: true }),
      list: vi.fn().mockResolvedValue([]),
      get: vi.fn().mockResolvedValue({ ok: false }),
      remove: vi.fn().mockResolvedValue({ ok: true, removed: 0 }),
      stats: vi.fn().mockResolvedValue({ total: 0, byKind: {}, sizeKB: 0 }),
    },
    planner: {
      create: vi.fn().mockResolvedValue({ ok: true }),
      list: vi.fn().mockResolvedValue([]),
      get: vi.fn().mockResolvedValue({ ok: false }),
      update: vi.fn().mockResolvedValue({ ok: true }),
      next: vi.fn().mockResolvedValue({ ok: false, error: "nenhuma tarefa pronta" }),
      run: vi.fn().mockResolvedValue({ ok: true, executed: [], counts: { total: 0, done: 0, failed: 0, pending: 0 } }),
      plan: vi.fn().mockResolvedValue({ ok: false, error: "plano vazio" }),
      review: vi.fn().mockResolvedValue({ ok: true, summary: { goalId: "g", total: 0, done: 0, failed: 0, tasks: [] } }),
      stats: vi.fn().mockResolvedValue({ total: 0, byStatus: {}, goals: 0 }),
    },
    agentHub: {
      list: vi.fn().mockResolvedValue([]),
      get: vi.fn().mockResolvedValue({ ok: false, error: "agente não encontrado" }),
      route: vi.fn().mockResolvedValue({ agent: null, reason: "" }),
      delegate: vi.fn().mockResolvedValue({ ok: false, error: "request é obrigatório", steps: [] }),
    },
    analytics: {
      summary: vi.fn().mockResolvedValue({
        system: { cpu: 0, memory: 0, disk: { freeGB: 0, totalGB: 0, usedPercent: 0 }, uptime: 0, platform: "win32", arch: "x64", hostname: "test" },
        counts: { conversations: 0, messages: 0, financeLog: 0, healthLog: 0, marketingLog: 0, agenda: 0, usageEvents: 0 },
        usage: { today: {}, total: {} },
        ai: { requests: 0, tokensIn: 0, tokensOut: 0 },
        telemetry: { counters: {}, metrics: {}, recentTraces: 0 },
        engines: { planner: null, memory: null, knowledge: null, skills: null },
      }),
      system: vi.fn().mockResolvedValue({ cpu: 0, memory: 0, disk: { freeGB: 0, totalGB: 0, usedPercent: 0 }, uptime: 0, platform: "win32", arch: "x64", hostname: "test" }),
      event: vi.fn().mockResolvedValue({ ok: true }),
    },
    sync: {
      status: vi.fn().mockResolvedValue({ connected: false }),
      trigger: vi.fn().mockResolvedValue({ ok: false }),
      test: vi.fn().mockResolvedValue({ ok: false }),
      configure: vi.fn().mockResolvedValue({ ok: false }),
    },
  },
  writable: true,
});

// Mock localStorage
const localStorageMock = (() => {
  let store: Record<string, string> = {};
  return {
    getItem: (key: string) => store[key] || null,
    setItem: (key: string, value: string) => { store[key] = value; },
    removeItem: (key: string) => { delete store[key]; },
    clear: () => { store = {}; },
  };
})();
Object.defineProperty(window, "localStorage", { value: localStorageMock });
} // end typeof window guard
